//! Textual-inspired reactive TUI framework built on rich-rs.

// Allow `textual::reactive::*` paths generated by `#[derive(Reactive)]` to
// resolve within this crate (same pattern as serde, tokio, etc.).
extern crate self as textual;

pub mod action;
pub mod animation;
pub mod compose;
pub mod content;
pub mod css;
pub mod debug;
pub mod demo_snapshot;
pub mod driver;
mod error;
pub mod event;
pub mod handle;
pub mod keys;
pub mod layout;
pub mod message;
pub mod message_handlers;
pub mod node_id;
pub mod reactive;
pub mod render;
pub mod renderables;
pub mod routing;
pub mod runtime;
pub mod screen;
pub mod signal;
pub mod style;
pub mod theme;
pub mod textual_app;
pub mod validation;
pub mod widget_tree;
pub mod widgets;
pub mod worker;

pub use error::{Error, Result};
pub use event::BindingHint;
pub use handle::{Handle, HandleSlot};
pub use keys::KeyEventData;
pub use node_id::{NodeId, node_id_from_ffi, node_id_to_ffi};
pub use reactive::ReactiveCtx;
pub use reactive::ReactiveWidget;
pub use runtime::{App, DomQuery, DomQueryMut, TimerHandle, TimerTick};
pub use screen::{Screen, ScreenMessageCtx, ScreenResult, ScreenResultCallback, ScreenStack};
pub use style::{Color, Style, Theme};
pub use theme::{NamedTheme, available_theme_names, get_theme, register_theme};
pub use runtime::Pilot;
pub use textual_app::{
    OverlayScreenStack, TextualApp, run, run_snapshot, run_snapshot_with_output, run_sync,
    run_sync_snapshot, run_sync_snapshot_with_output, run_sync_with_output, run_test,
    run_test_sized, run_textual_app, run_textual_app_or_snapshot,
    run_textual_app_or_snapshot_with_output, run_textual_app_with_output,
};
pub use textual_macros::Reactive;
pub use textual_macros::on;
pub use textual_macros::widget;
pub use widgets::BindingDecl;
pub use widgets::WidgetStyles;

pub mod prelude {
    pub use crate::action::{ActionDecl, ActionHandler, ParsedAction, parse_action};
    pub use crate::animation::{Animator, animation_level_from_env};
    pub use crate::compose::{ChildDecl, ComposeResult, WidgetBuilder};
    // NOTE: `HandleSink` is intentionally NOT in the prelude (RA2.6b) — it is
    // compose-pipeline plumbing; reach it via `crate::handle::HandleSink`.
    pub use crate::handle::{Handle, HandleSlot};
    pub use crate::css::{StyleSelector, StyleSheet, resolve_component_style, set_style_context};
    pub use crate::debug::DebugLayout;
    // NOTE: `EventCtx` is intentionally NOT in the prelude (RA2.2). It is now
    // internal/structural — the runtime synthesizes it and `WidgetCtx` wraps it;
    // widget handlers receive `WidgetCtx`. Reach `EventCtx` via `crate::event::EventCtx`
    // for the rare internal/adapter that needs it directly.
    pub use crate::event::{
        Action, ActionMap, AnimationEase, BindingHint, ClassOp, ClickEvent, Event, KeyBind,
        MouseEnterEvent, MouseLeaveEvent, PasteEvent, WidgetCtx,
    };
    pub use crate::keys::{KeyEventData, format_key_display, key_to_identifier};
    pub use crate::message::*;
    pub use crate::message_handlers::{MessageContext, MessageHandlers};
    pub use crate::node_id::{NodeId, node_id_from_ffi, node_id_to_ffi};
    // NOTE (RA2.6b): `ControlMeta`, `Selector`, `SelectorParseError` are routing
    // internals — reach them via `crate::routing::` if truly needed.
    pub use crate::routing::MessageRouter;
    // NOTE (RA2.6b): the tree-plumbing entry points (`build_widget_tree_from_root`,
    // `dispatch_*_tree`, `render_tree_to_frame*`, `run_layout_pass`,
    // `focused_node_id_tree`) and `DispatchOutcome` are runtime internals, NOT user
    // API — user apps go through `TextualApp`/`Pilot`/`run_test`. Harness-level code
    // that drives trees directly imports them via `textual::runtime::{...}`.
    pub use crate::runtime::{
        App, CallFromThreadError, DomQuery, DomQueryMut, PushScreenWaitError,
        TimerHandle, TimerTick, WidgetQuery,
    };
    pub use crate::screen::{
        Screen, ScreenMessageCtx, ScreenResult, ScreenResultCallback, ScreenStack,
    };
    pub use crate::reactive::{ReactiveChange, ReactiveCtx, ReactiveFlags, ReactiveWidget};
    pub use crate::signal::{Signal, SignalResponse};
    pub use crate::content::Content;
    pub use crate::style::{Color, Style, TextAlign, Theme};
    pub use crate::theme::{NamedTheme, available_theme_names, get_theme, register_theme};
    pub use textual_macros::Reactive;
    pub use textual_macros::widget;
    pub use crate::runtime::Pilot;
    pub use crate::textual_app::{
        OverlayScreenStack, TextualApp, run, run_snapshot, run_snapshot_with_output, run_sync,
        run_sync_snapshot, run_sync_snapshot_with_output, run_sync_with_output, run_test,
        run_test_sized, run_textual_app, run_textual_app_or_snapshot,
        run_textual_app_or_snapshot_with_output, run_textual_app_with_output,
    };
    pub use crate::validation::{
        Function, Integer, Length, Number, Regex, Url, ValidationResult, Validator, ValidatorRef,
    };
    pub use crate::widget_tree::{LifecycleEvent, QueryError, WidgetNode, WidgetTree};
    #[allow(deprecated)] // `Node` is deprecated (RA2.6) but re-exported for one release.
    pub use crate::widgets::{
        AppRoot, BindingDecl, BindingsTable, Button, ButtonVariant,
        Cell as DataTableCell, CellJustify, Center,
        CenterMiddle, Checkbox, Collapsible, CollapsibleTitle, CommandPalette,
        Constrained,
        Container, ContentSwitcher, CursorType, DataTable, Digits, DirectoryTree, Dock, Footer,
        FooterBinding, Frame, FuzzyMatcher, Grid, Header, HeaderClock, HeaderClockSpace,
        HeaderIcon, HeaderTitle, HelpPanel, Horizontal, HorizontalGroup, HorizontalScroll, Input,
        InputType, ItemGrid, KeyPanel, Label, LabelVariant, LayoutConstraints, LineStyle, Link,
        ListItem, ListView, LoadingIndicator, Log, Markdown, MarkdownTableOfContents,
        MarkdownViewer, MaskedInput, Middle, Node, NodeSeed, NodeState, OptionContent, OptionId,
        OptionItem, OptionList,
        Overlay, PaletteCommand, Panel, Placeholder, PlaceholderVariant, Pretty, ProgressBar,
        RadioButton, RadioSet, RichLog, Right, Row, RowAlign, Rule, RuleOrientation, ScrollBar,
        ScrollBarCorner, ScrollBarRender, ScrollDirectionMessage, ScrollTo, ScrollView,
        ScrollableContainer, Select, Selection, SelectionList, SelectionListString, SortKey, Spacer,
        Sparkline, Static, StyleChangeKind, Styled, SuggestFromList, Suggester, SummaryFunction,
        Switch, SystemModalScreen, TabPane, TabbedContent, Tabs, TextArea, TextAreaCursor,
        TextAreaSelection, TextAreaTheme, Toast, ToastSeverity, Tooltip, Tree, TreeNode, Vertical,
        VerticalGroup, VerticalScroll, Welcome, Widget, WidgetRenderable, WidgetStyles,
        // NOTE (RA2.6b): the legacy delegate macros (`delegate_widget_to`,
        // `delegate_widget_method`, `delegate_renderable`) and
        // `classify_style_change` are out of the prelude — `#[widget(base = ...)]`
        // is the supported delegation surface. `CommandPaletteScreen` (a dead
        // never-wired wrapper) is also out, pending the palette modal-screen
        // rebuild. All remain reachable via `crate::widgets::` for one release.
        preview_root, preview_root_with_bottom, preview_root_with_top_bottom, summary_max,
        summary_mean, summary_min,
    };
    pub use crate::worker::{
        CancellationToken, WorkerId, WorkerRegistry, WorkerRequest, WorkerState,
    };
    pub use crate::{Error, Result};
}
